<?php
$languages = [
    'vi' => [
        'home' => 'Trang chủ',
        'products' => 'Sản phẩm',
        'brands' => 'Thương hiệu',
        'login' => 'Đăng nhập',
        'register' => 'Đăng ký',
        'cart' => 'Giỏ hàng',
        'logout' => 'Đăng xuất',
        'search' => 'Tìm kiếm sản phẩm...',
        'new_season' => 'Mùa mới 2026',
        'hero_title' => 'Bước Đi Đẳng Cấp Nâng Tầm Phong Cách.',
        'hero_subtitle' => 'Khám phá bộ sưu tập sneakers giới hạn với công nghệ đệm khí tiên tiến nhất.',
        'buy_now' => 'Mua Ngay',
        'featured_categories' => 'Danh Mục Nổi Bật',
        'best_seller' => 'Sản Phẩm Bán Chạy',
        'add_to_cart' => 'Thêm vào giỏ',
        'all_products' => 'Xem tất cả',
        'newsletter_title' => 'Đăng Ký Nhận Ưu Đãi 20%',
        'newsletter_btn' => 'ĐĂNG KÝ',
        'shipping_free' => 'Miễn phí vận chuyển',
        'genuine' => 'Chính hãng 100%',
        'support' => 'Hỗ trợ 24/7',
        'admin_dashboard' => 'Bảng điều khiển',
        'admin_products' => 'Sản phẩm',
        'admin_orders' => 'Đơn hàng'
    ],
    'en' => [
        'home' => 'Home',
        'products' => 'Products',
        'brands' => 'Brands',
        'login' => 'Login',
        'register' => 'Register',
        'cart' => 'Cart',
        'logout' => 'Logout',
        'search' => 'Search products...',
        'new_season' => 'New Season 2026',
        'hero_title' => 'Step Up Your Style With Premium Sneakers.',
        'hero_subtitle' => 'Discover limited sneakers collections with the most advanced cushioning technology.',
        'buy_now' => 'Shop Now',
        'featured_categories' => 'Featured Categories',
        'best_seller' => 'Best Sellers',
        'add_to_cart' => 'Add to Cart',
        'all_products' => 'View All',
        'newsletter_title' => 'Subscribe & Get 20% Off',
        'newsletter_btn' => 'SUBSCRIBE',
        'shipping_free' => 'Free Shipping',
        'genuine' => '100% Genuine',
        'support' => '24/7 Support',
        'admin_dashboard' => 'Dashboard',
        'admin_products' => 'Products',
        'admin_orders' => 'Orders'
    ]
];
?>
